"""update_vector_dim_to_768

Revision ID: 27e71befb5b8
Revises: 001
Create Date: 2026-07-22 19:33:19.469864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '27e71befb5b8'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Clear existing dummy embeddings to avoid dimension mismatch when casting
    op.execute('UPDATE images SET embedding = NULL')
    
    op.drop_index('idx_api_keys_user_id', table_name='api_keys')
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.drop_index('idx_captions_image_id', table_name='captions')
    op.create_index(op.f('ix_captions_image_id'), 'captions', ['image_id'], unique=False)
    op.add_column('images', sa.Column('caption', sa.Text(), nullable=True))
    op.add_column('images', sa.Column('processing_time_ms', sa.Float(), nullable=True))
    op.alter_column('images', 'embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=1024),
               type_=pgvector.sqlalchemy.Vector(dim=768),
               existing_nullable=True)
    op.drop_index('idx_images_anon_session_id', table_name='images')
    op.drop_index('idx_images_embedding', table_name='images', postgresql_using='ivfflat')
    op.drop_index('idx_images_user_id', table_name='images')
    op.create_index(op.f('ix_images_anon_session_id'), 'images', ['anon_session_id'], unique=False)
    op.create_index(op.f('ix_images_user_id'), 'images', ['user_id'], unique=False)
    op.drop_index('idx_jobs_image_id', table_name='jobs')
    op.create_index(op.f('ix_jobs_image_id'), 'jobs', ['image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_image_id'), table_name='jobs')
    op.create_index('idx_jobs_image_id', 'jobs', ['image_id'], unique=False)
    op.drop_index(op.f('ix_images_user_id'), table_name='images')
    op.drop_index(op.f('ix_images_anon_session_id'), table_name='images')
    op.create_index('idx_images_user_id', 'images', ['user_id'], unique=False)
    op.create_index('idx_images_embedding', 'images', ['embedding'], unique=False, postgresql_using='ivfflat')
    op.create_index('idx_images_anon_session_id', 'images', ['anon_session_id'], unique=False)
    op.alter_column('images', 'embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=768),
               type_=pgvector.sqlalchemy.Vector(dim=1024),
               existing_nullable=True)
    op.drop_column('images', 'processing_time_ms')
    op.drop_column('images', 'caption')
    op.drop_index(op.f('ix_captions_image_id'), table_name='captions')
    op.create_index('idx_captions_image_id', 'captions', ['image_id'], unique=False)
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.create_index('idx_api_keys_user_id', 'api_keys', ['user_id'], unique=False)
    # ### end Alembic commands ###
